---
senlin-services:
  senlin-api:
    group: senlin-api
    enabled: true
  senlin-conductor:
    group: senlin-conductor
    enabled: true
  senlin-engine:
    group: senlin-engine
    enabled: true
  senlin-health-mananager:
    group: senlin-health-mananager
    enabled: true

####################
# Database
####################
senlin_database_name: "senlin"
senlin_database_user: "{% if use_preconfigured_databases | bool and use_common_mariadb_user | bool %}{{ database_user }}{% else %}senlin{% endif %}"
senlin_database_address: "{{ database_address | put_address_in_context('url') }}:{{ database_port }}"


####################
# OpenStack
####################
senlin_admin_endpoint: "{{ admin_protocol }}://{{ senlin_internal_fqdn | put_address_in_context('url') }}:{{ senlin_api_port }}"
senlin_internal_endpoint: "{{ internal_protocol }}://{{ senlin_internal_fqdn | put_address_in_context('url') }}:{{ senlin_api_port }}"
senlin_public_endpoint: "{{ public_protocol }}://{{ senlin_external_fqdn | put_address_in_context('url') }}:{{ senlin_api_port }}"

senlin_logging_debug: "{{ openstack_logging_debug }}"

senlin_keystone_user: "senlin"

openstack_senlin_auth: "{{ openstack_auth }}"

####################
# Notifications
####################
senlin_notification_topics:
  - name: notifications
    enabled: "{{ enable_ceilometer | bool }}"

senlin_enabled_notification_topics: "{{ senlin_notification_topics | selectattr('enabled', 'equalto', true) | list }}"

####################
# Keystone
####################
senlin_ks_services:
  - name: "senlin"
    type: "clustering"
    description: "Senlin Clustering Service"
    endpoints:
      - {'interface': 'admin', 'url': '{{ senlin_admin_endpoint }}'}
      - {'interface': 'internal', 'url': '{{ senlin_internal_endpoint }}'}
      - {'interface': 'public', 'url': '{{ senlin_public_endpoint }}'}

senlin_ks_users:
  - project: "service"
    user: "{{ senlin_keystone_user }}"
    password: "{{ senlin_keystone_password }}"
    role: "admin"